# Generated by Django 4.1.7 on 2023-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlotInputFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=2000)),
                ('logline', models.CharField(default='', max_length=2000)),
                ('Themes', models.CharField(default='', max_length=2000)),
                ('StoryTypes', models.CharField(default='', max_length=2000)),
                ('Genres', models.CharField(default='', max_length=2000)),
                ('Tone', models.CharField(default='', max_length=2000)),
                ('Audience', models.CharField(default='', max_length=2000)),
                ('B_Story', models.CharField(default='', max_length=2000)),
                ('Setting', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
